# Generated by Django 5.2.5 on 2025-08-14 17:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Em andamento'), ('high', 'Concluído')], default='low', max_length=10)),
                ('sector', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'Atendentes'), ('in_progress', 'Técnicos'), ('completed', 'Técnicos')], default='open', max_length=11)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
            },
        ),
    ]
