# Generated by Django 5.2.5 on 2025-08-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Atendentes'), ('in_progress', 'Técnicos'), ('completed', 'Completos')], default='open', max_length=11),
        ),
    ]
